services:
  app:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-api
    restart: always
    environment:
      MODE: native
    ports:
      - "8080:8080"
    volumes:
      - "./data/signal-api:/home/.local/share/signal-cli"
  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
